### PR TITLE
Allow users to change their passwords while signed in

### PR DESCRIPTION
**Pull request by flanger001**
This is directly related to an email correspondence with Chris Hunt.

My basic steps were:
1. Write tests
2. `rails generate devise:views -v registrations`
3. Edit `routes.rb` and appropriate view files
4. Tests pass yay

I saw this also allows people to change their email address, but I do not know if this is something you want to allow. The password change functionality has test coverage, but the email change functionality does not.

As this is my first PR for any OSS project ever, I would love any feedback you can provide!

### CODE REVIEW

**Comment by r00k** [comment]
Thanks for the pull!

I can take a look in roughly 24 hours, unless @chrishunt gets to it before then.

**Comment by flanger001** [comment]
Hello! I see there are a bunch of Travis CI errors, but they are only for indentation and hash syntax. Would you like me to fix these? If so, feel free to reject the pull and I'll do that. I can also try again with my tests if they are not up to snuff.

**Comment by flanger001** [comment]
I hit close by mistake; I will leave it to you to reopen if you want.

**Comment by r00k** [comment]
Hi there! 

Sorry about us being slow, but yes, please do fix the Hound errors. We like to keep the style consistent in our repo.

Once that's done, please ping me once more and I'll take a look!

**Pull request closed without merging**
